apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: sdsds
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: sdsds
    version: v1.0.0
    applicationId: app_e3f985af-b90c-4294-9646-81b22800e8e3
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_055fba93-58d5-43d7-aaad-c684411e22b9
    environmentName: prod
  namespace: iwiick-brean-and-brew-prod
