apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: ecf159d1d0800414cb48ddfb854a1604823b51d6
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: coffee-cart-service-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/coffee-cart-service
      credentialId: credential_ab11a1fb-aae1-4082-803a-71f10b238b12
      commitDetails:
        commitHash: ecf159d1d0800414cb48ddfb854a1604823b51d6
        commitAvatar: https://github.com/iwiick.png
        commitTime: 2024-06-17T10:56:22 05:30
        commitMessage: >-
          Delete
          .github/workflows/container-staging_app_6f75d8c_env_28f618a.yaml
        commitUser: iwiick
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: coffee-cart-service
    version: v1.0.0
    applicationId: app_6f75d8cd-0b9b-402f-8ee6-ae6f28aae89a
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_89269fe4-4d15-47ea-b6ea-94e25be133b2
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: coffee-cart-service
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-local-dev
