apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: coffee-user-service-v1-0-0
  labels:
    app: coffee-user-service-v1-0-0
    applicationId: app_3e895955-403a-4e75-a839-d6b85801f37d
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffee-user-service-v1-0-0
