apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: coffee-order-service-v1-0-0
  labels:
    app: coffee-order-service-v1-0-0
    applicationId: app_bf246db8-82e8-4651-a0e4-6360aad0f715
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffee-order-service-v1-0-0
