apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: pasan-ai-test-v1-0-0
    applicationId: app_0e790088-e961-46d8-b44b-0448f87fa8dc
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_1a87bd72-0386-4592-aa0d-74a082510bbc
  name: pasan-ai-test-v1-0-0
spec:
  selector:
    app: pasan-ai-test-v1-0-0
