apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: pasan-test-github-vc-v1-0-0
    applicationId: app_93cd99d2-9ce0-4295-be9f-5d18048a699f
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_1a87bd72-0386-4592-aa0d-74a082510bbc
  name: pasan-test-github-vc-v1-0-0
spec:
  selector:
    app: pasan-test-github-vc-v1-0-0
