apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: pasan-test-github-vc-v1-0-0
  labels:
    app: pasan-test-github-vc-v1-0-0
    applicationId: app_93cd99d2-9ce0-4295-be9f-5d18048a699f
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pasan-test-github-vc-v1-0-0
