apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: jayani-ai-service-testing-v1-0-0
  labels:
    app: jayani-ai-service-testing-v1-0-0
    applicationId: app_eda38f82-0c87-4299-b747-a0d4d315e1db
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jayani-ai-service-testing-v1-0-0
