apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-catalog-service-v1-0-0
  labels:
    app: coffee-catalog-service-v1-0-0
    applicationId: app_8654f202-8484-4d89-aa30-7c169fed96fa
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: coffee-catalog-service-v1-0-0
  template:
    metadata:
      labels:
        app: coffee-catalog-service-v1-0-0
        applicationId: app_8654f202-8484-4d89-aa30-7c169fed96fa
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
