apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: sameerademoapp-v1-0-0
  labels:
    app: sameerademoapp-v1-0-0
    applicationId: app_bb411bc1-875f-46ae-8a3d-9d2980b9c1a7
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sameerademoapp-v1-0-0
