apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: pasan-ai-test-v1-0-0
  labels:
    app: pasan-ai-test-v1-0-0
    applicationId: app_0e790088-e961-46d8-b44b-0448f87fa8dc
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_055fba93-58d5-43d7-aaad-c684411e22b9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pasan-ai-test-v1-0-0
