apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts:
        - configMapName: dfgdfg
          isEnv: false
          isFile: true
          key: dfgdf
          mountPath: dfgdfg
          secretName: ''
      applicationPorts: []
      healthChecks: []
      name: sameerademoapp-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/sameera-demo-cronjob-app
      credentialId: credential_0d2b12d4-51b2-458e-b30d-2aec45476070
    - name: dfgfg
      imagePullPolicy: Always
      imageRegistry: dfgdfg
      applicationPorts: []
      cpuRequestMili: 100
      cpuLimitMili: 2000
      memoryRequestMb: 100
      memoryLimitMb: 1000
      command: []
      args: []
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: sameerademoapp
    version: v1.0.0
    applicationId: app_bb411bc1-875f-46ae-8a3d-9d2980b9c1a7
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: SameeraDemoApp
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-dev
