apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: test-config
  namespace: iwiick-brean-and-brew-dev
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
spec:
  data:
    config.json: ${{secret::secret_8f739795-1f73-46ae-86e7-840e12445a98:}}
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
