apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-cred-check-2-v1-0-0
  labels:
    app: iwiick-cred-check-2-v1-0-0
    applicationId: app_c27452a3-4bd0-4299-a175-9d9df40a41f3
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-cred-check-2-v1-0-0
