apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 2d69fc6dc305d0a3de932ed825ac34aa7cd4410e
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: coffee-user-service-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/coffee-user-service
      credentialId: credential_ab11a1fb-aae1-4082-803a-71f10b238b12
      commitDetails:
        commitHash: 2d69fc6dc305d0a3de932ed825ac34aa7cd4410e
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-06-17T05:23:17Z'
        commitMessage: SkyU container Template Workflows Created
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: coffee-user-service
    version: v1.0.0
    applicationId: app_3e895955-403a-4e75-a839-d6b85801f37d
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_89269fe4-4d15-47ea-b6ea-94e25be133b2
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: coffee-user-service
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-local-dev
