apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: coffee-cart-service-v1-0-0
  labels:
    app: coffee-cart-service-v1-0-0
    applicationId: app_6f75d8cd-0b9b-402f-8ee6-ae6f28aae89a
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffee-cart-service-v1-0-0
