apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: coffee-shop-v1-0-0
    applicationId: app_5dec74eb-c7c7-4d92-a5f7-3576bde2f861
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
  name: coffee-shop-v1-0-0
spec:
  selector:
    app: coffee-shop-v1-0-0
