apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: hrlmtest
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: hrlmtest
    version: v1.0.0
    applicationId: app_5567dc03-fc8a-4147-88c7-ee57404ffb8f
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_1a87bd72-0386-4592-aa0d-74a082510bbc
    environmentName: staging
  namespace: iwiick-brean-and-brew-staging
