apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: qa-coffee-cart-svc-test-v1-0-0
    applicationId: app_3cd18076-3766-4239-9262-6418eae8f03d
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_055fba93-58d5-43d7-aaad-c684411e22b9
  name: qa-coffee-cart-svc-test-v1-0-0
spec:
  selector:
    app: qa-coffee-cart-svc-test-v1-0-0
