apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: testhelm-v1-0-0-staging-secret
  namespace: iwiick-brean-and-brew-staging
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_1a87bd72-0386-4592-aa0d-74a082510bbc
    applicaitonId: app_de6d26f4-2786-4ba1-8da1-3743d931646c
spec:
  data:
    test: ${{secret::secret_42fee9f3-dc6e-4dc3-ad93-c765cfe17219:}}
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
