apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 37f5801401823d7f991d927e2357750dd27a2f88
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 5002
          targetPort: 5002
          protocol: TCP
          apiSpec:
            gitPath: swagger-specification.yml
      healthChecks: []
      name: cart-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/cart
      credentialId: credential_0d2b12d4-51b2-458e-b30d-2aec45476070
      commitDetails:
        commitHash: 37f5801401823d7f991d927e2357750dd27a2f88
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-07-06T09:10:21Z'
        commitMessage: container-dev_app_3203294_env_31ddbbd.yaml Updated
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: cart
    version: v1.0.0
    applicationId: app_3203294f-aeb4-4a31-b8fd-754829df4fda
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: cart
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-dev
  serviceAccountName: service-account-3
