apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-helm-demo-v1-0-0
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    applicaitonId: app_dedee9fa-c689-45c4-80bc-303a0d7e8b3b
spec:
  interval: 1m0s
  url: https://github.com/Ridmi-INS/charts
  ref:
    branch: main
  secretRef:
    name: test-helm-demo-v1-0-0-secret
