apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: efeebaad1019e21c103bbb3a8882e411af21ee5c
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: order-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/order
      credentialId: credential_0d2b12d4-51b2-458e-b30d-2aec45476070
      commitDetails:
        commitHash: efeebaad1019e21c103bbb3a8882e411af21ee5c
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-06-24T06:16:56Z'
        commitMessage: Update swagger documentation
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: order
    version: v1.0.0
    applicationId: app_9a8abf89-baa4-4ee8-9dc3-919c87aaa84d
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: order
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-dev
