apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-service-2-v1-0-0
  labels:
    app: test-service-2-v1-0-0
    applicationId: app_dd82c07b-c816-4b1c-a760-e9f0790d78b4
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-service-2-v1-0-0
