apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: pasan-test-swa-v1-0-0
    applicationId: app_6cbd0d53-7034-4837-8204-ee4acd827ff4
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
  name: pasan-test-swa-v1-0-0
spec:
  selector:
    app: pasan-test-swa-v1-0-0
