apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: coffee-user-service-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/coffee-user-service
      credentialId: credential_ab11a1fb-aae1-4082-803a-71f10b238b12
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: coffee-user-service
    version: v1.0.0
    applicationId: app_3e895955-403a-4e75-a839-d6b85801f37d
    projectId: project_2db65eb5-fb3b-48f3-a016-1edf7e9e473c
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_2f8d71c0-01e8-4ae7-8cf4-4d209df82192
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: coffee-user-service
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-brean-and-brew-local-prod
