apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: insightstest
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: insightstest
    version: v1.0.0
    applicationId: app_1c7727d0-e5a2-4454-b520-c8522cba2a42
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
    environmentName: dev
  namespace: iwiick-brean-and-brew-dev
