apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: shop-v1-0-0
  labels:
    app: shop-v1-0-0
    applicationId: app_5cd994ca-6334-4fa0-a4c1-55c4e43a689d
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-v1-0-0
