apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwiick-cred-check-v1-0-0
  labels:
    app: iwiick-cred-check-v1-0-0
    applicationId: app_7f8a2665-2484-4f1b-82a2-d7dab49e5ffd
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: iwiick-cred-check-v1-0-0
  template:
    metadata:
      labels:
        app: iwiick-cred-check-v1-0-0
        applicationId: app_7f8a2665-2484-4f1b-82a2-d7dab49e5ffd
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
        environmentId: env_31ddbbde-7bfc-4d60-89f4-920f8e416be0
