apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: amaan-ai-repo-service-testing-v1-0-0
  labels:
    app: amaan-ai-repo-service-testing-v1-0-0
    applicationId: app_59b0372d-dfe5-4b4a-8e5a-4d98bb38149f
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_78bf2621-6ba3-4cd7-963a-058179ce0ef9
    environmentId: env_055fba93-58d5-43d7-aaad-c684411e22b9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amaan-ai-repo-service-testing-v1-0-0
